# Generated by Django 4.2.3 on 2023-09-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=30)),
                ("category", models.CharField(max_length=30)),
                ("mandate", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=30)),
                ("size", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=30)),
                ("occasion", models.CharField(max_length=30)),
                ("image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Registartion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("number", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stallionz.login",
                    ),
                ),
            ],
        ),
    ]
