# Generated by Django 4.2.3 on 2023-09-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registartion",
            name="role",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
