# Generated by Django 4.2.3 on 2023-10-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pyment_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("statuz", models.CharField(max_length=20)),
                ("grandtotal", models.CharField(max_length=20)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stallionz.login",
                    ),
                ),
            ],
        ),
    ]
