# Generated by Django 4.2.3 on 2023-09-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0002_registartion_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productid", models.CharField(max_length=30)),
                ("userid", models.CharField(max_length=30)),
                ("quantity", models.CharField(max_length=30)),
                ("ststus", models.CharField(max_length=30)),
            ],
        ),
    ]
