# Generated by Django 4.2.3 on 2023-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0004_final_pyment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="final_pyment",
            name="userid",
            field=models.CharField(max_length=20),
        ),
    ]
