# Generated by Django 4.2.3 on 2023-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0005_alter_final_pyment_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="place_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=20)),
            ],
        ),
    ]
