# Generated by Django 4.2.3 on 2023-11-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0006_place_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="place_order",
            name="category",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="color",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="gender",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="image",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="productid",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="productname",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="quantity",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="size",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
