# Generated by Django 4.2.3 on 2023-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0007_place_order_category_place_order_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place_order",
            name="grandtotal",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place_order",
            name="pyment_status",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
