# Generated by Django 4.2.3 on 2023-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0008_place_order_grandtotal_place_order_pyment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="place_order",
            name="order_status",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
