# Generated by Django 4.2.3 on 2023-11-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0009_place_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="final_pyment",
            name="category",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="final_pyment",
            name="color",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="final_pyment",
            name="gender",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="final_pyment",
            name="image",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="final_pyment",
            name="productid",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="final_pyment",
            name="productname",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="final_pyment",
            name="quantity",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="final_pyment",
            name="size",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
