# Generated by Django 4.2.3 on 2023-11-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0010_final_pyment_category_final_pyment_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place_order",
            name="pyment_status",
        ),
    ]
