# Generated by Django 4.2.3 on 2023-11-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0011_remove_place_order_pyment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="final_pyment",
            name="pyment_type",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
