# Generated by Django 4.2.3 on 2024-01-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stallionz", "0012_final_pyment_pyment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="final_pyment",
            name="color",
        ),
    ]
